language: go

go:
  - "1.11"

before_install:
  - go get -u github.com/modocache/gover
  - go get -u github.com/mattn/goveralls

after_success:
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

env:
  - GO111MODULE=on
