[[constraint]]
name = "github.com/kr/text"
version = "0.1.0"

[[constraint]]
branch = "master"
name = "github.com/lithammer/dedent"

[[constraint]]
name = "github.com/stretchr/testify"
version = "1.2.2"

[[constraint]]
branch = "master"
name = "github.com/texttheater/golang-levenshtein"
